[project]
name = "polars-definitive-guide"
version = "0.1.0"
description = "Polars definitive guide book notes"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "plotnine>=0.14.5",
    "polars>=1.30.0",
    "quarto>=0.1.0",
]
